---
- name: Create Actual Budget volume
  community.docker.docker_volume:
    state: present
    volume_name: actual_data

- name: Run Actual Budget container
  community.docker.docker_container:
    name: actual-budget
    image: ghcr.io/actualbudget/actual:latest
    state: started
    pull: always
    recreate: true
    restart_policy: unless-stopped
    networks:
      - name: traefik_network
    volumes:
      - actual_data:/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.actual.rule: Host(`actual.{{ traefik_domain }}`)
      traefik.http.routers.actual.entrypoints: "websecure"
      traefik.http.routers.actual.service: "actual"
      traefik.http.services.actual.loadbalancer.server.port: "5006"