---
- name: Create Termix volume
  community.docker.docker_volume:
    state: present
    volume_name: termix_data

- name: Run Termix container
  community.docker.docker_container:
    name: termix
    image: ghcr.io/lukegus/termix:latest
    state: started
    pull: always
    recreate: true
    restart_policy: unless-stopped
    networks:
      - name: traefik_network
    volumes:
      - termix_data:/app/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.termix.rule: Host(`ssh.{{ traefik_domain }}`)
      traefik.http.routers.termix.entrypoints: "websecure"
      traefik.http.routers.termix.service: "termix"
      traefik.http.services.termix.loadbalancer.server.port: "8080"