---
- name: Set default policy for incoming traffic
  community.general.ufw:
    direction: incoming
    default: deny
    
- name: Set default policy for outgoing traffic
  community.general.ufw:
    direction: outgoing
    default: allow
    
- name: Limit SSH traffic
  community.general.ufw:
    rule: limit
    port: ssh

- name: Allow HTTP/HTTPS traffic
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - http
    - https
  when: inventory_hostname == "vm-docker"

- name: Enable UFW and log everything
  community.general.ufw:
    state: enabled
    logging: on