---
- name: Create Docker NFS volume for Jellyfin
  community.docker.docker_volume:
    state: present
    volume_name: jellyfin_nfs
    driver_options:
      type: "nfs"
      o: "addr={{ hostvars['srv-truenas']['ansible_host'] }}"
      device: ":/mnt/default-pool/jellyfin"

- name: Create Jellyfin volumes
  community.docker.docker_volume:
    state: present
    volume_name: "{{ item }}"
  loop:
    - jellyfin_config
    - jellyfin_cache

- name: Run Jellyfin container
  community.docker.docker_container:
    name: jellyfin
    image: docker.io/jellyfin/jellyfin:latest
    state: started
    pull: always
    recreate: true
    restart_policy: unless-stopped
    networks:
      - name: traefik_network
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - jellyfin_nfs:/mnt:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.{{ traefik_domain }}`)
      traefik.http.routers.jellyfin.entrypoints: "websecure"
      traefik.http.routers.jellyfin.service: "jellyfin"
      traefik.http.services.jellyfin.loadbalancer.server.port: "8096"