---
- name: Create Traefik directory
  ansible.builtin.file:
    path: "/mnt/traefik_data"
    state: directory
    owner: '1000'
    group: '1000'

- name: Template Traefik configuration
  ansible.builtin.template:
    src: "traefik.yml.j2"
    dest: "/mnt/traefik_data/traefik.yml"
    owner: '1000'
    group: '1000'

- name: Create acme.json file
  ansible.builtin.file:
    path: "/mnt/traefik_data/acme.json"
    state: touch
    owner: '1000'
    group: '1000'
    mode: '0600'

- name: Create the reverse-proxy network
  community.docker.docker_network:
    name: traefik_network

- name: Run traefik container
  community.docker.docker_container:
    name: traefik
    image: docker.io/library/traefik:latest
    state: started
    pull: always
    recreate: true
    restart_policy: unless-stopped
    networks:
      - name: traefik_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/traefik_data:/etc/traefik
    env:
      OVH_ENDPOINT: "{{ ovh_endpoint }}"
      OVH_APPLICATION_KEY: "{{ ovh_application_key }}"
      OVH_APPLICATION_SECRET: "{{ ovh_application_secret }}"
      OVH_CONSUMER_KEY: "{{ ovh_consumer_key }}"